### ISSUE TITLE
Kibana deployment failure

### ISSUE THREAD

**Issue by vishnudxb** [wazuh/wazuh-kubernetes#167]
I am getting an error when deploying kibana (Image: wazuh/wazuh-kibana-odfe:4.1.5). Looks like a bug in the Kibana API ? 

```
➜  kubectl logs -f wazuh-kibana-55878ddcb6-9pxpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    37  100    37    0     0     99      0 --:--:-- --:--:-- --:--:--    98
Elasticsearch is up.
Wazuh alerts template not loaded - sleeping.
Wazuh alerts template is loaded.
Open Distro Security not initialized.Waiting for Kibana API. Sleeping 5 seconds
Waiting for Kibana API. Sleeping 5 seconds
Waiting for Kibana API. Sleeping 5 seconds
{"type":"log","@timestamp":"2021-06-23T02:23:35Z","tags":["info","plugins-service"],"pid":25,"message":"Plugin \"telemetryManagementSection\" has been disabled since the following direct or transitive dependencies are missing or disabled: [telemetry]"}
{"type":"log","@timestamp":"2021-06-23T02:23:35Z","tags":["info","plugins-service"],"pid":25,"message":"Plugin \"newsfeed\" is disabled."}
{"type":"log","@timestamp":"2021-06-23T02:23:35Z","tags":["info","plugins-service"],"pid":25,"message":"Plugin \"telemetry\" is disabled."}
{"type":"log","@timestamp":"2021-06-23T02:23:35Z","tags":["info","plugins-service"],"pid":25,"message":"Plugin \"visTypeXy\" is disabled."}
{"type":"log","@timestamp":"2021-06-23T02:23:35Z","tags":["warning","config","deprecation"],"pid":25,"message":"\"cpu.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuPath\""}
{"type":"log","@timestamp":"2021-06-23T02:23:35Z","tags":["warning","config","deprecation"],"pid":25,"message":"\"cpuacct.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuAcctPath\""}
{"type":"log","@timestamp":"2021-06-23T02:23:35Z","tags":["warning","config","deprecation"],"pid":25,"message":"\"server.defaultRoute\" is deprecated and has been replaced by \"uiSettings.overrides.defaultRoute\""}
{"type":"log","@timestamp":"2021-06-23T02:23:35Z","tags":["fatal","root"],"pid":25,"message":"Error: error:0909006C:PEM routines:get_name:no start line\n    at Object.createSecureContext (_tls_common.js:156:17)\n    at Server (_tls_wrap.js:903:27)\n    at new Server (https.js:62:14)\n    at Object.createServer (https.js:85:10)\n    at module.exports.internals.Core._createListener (/usr/share/kibana/node_modules/hapi/lib/core.js:491:79)\n    at new module.exports.internals.Core (/usr/share/kibana/node_modules/hapi/lib/core.js:112:30)\n    at new module.exports (/usr/share/kibana/node_modules/hapi/lib/server.js:25:18)\n    at createServer (/usr/share/kibana/src/core/server/http/http_tools.js:113:18)\n    at HttpServer.setup (/usr/share/kibana/src/core/server/http/http_server.js:94:48)\n    at HttpService.runNotReadyServer (/usr/share/kibana/src/core/server/http/http_service.js:162:26)\n    at HttpService.setup (/usr/share/kibana/src/core/server/http/http_service.js:78:18)"}

 FATAL  Error: error:0909006C:PEM routines:get_name:no start line
```

**Comment by teddytpc1** [comment]
Hi @vishnudxb.
Would you tell me if you were able to resolve this issue?
In case you were not please let me know:
- The documentation and steps you used to deploy Wazuh in K8s.
- How did you generate the certificates? There are two script to create certificates (`wazuh/certs/odfe_cluster/generate_certs.sh` and `wazuh/certs/kibana_http/generate_certs.sh`), did you use them? If not, please try generating the certificates with those scripts and redeploying Wazuh.
- Have you tried deploying the latest Wazuh version using tag `v4.2.4`?
