### ISSUE TITLE
Dashboard OpenID support 

### ISSUE THREAD

**Issue by victorrodriguez1984** [wazuh/wazuh-kubernetes#317]
Version:
tested on 4.3.9 and 4.3.10

Issue:
OpenID config based in Opensearch documentation does not work
https://opensearch.org/docs/latest/security-plugin/configuration/openid-connect/
https://www.linkedin.com/pulse/integrate-opensearch-azure-active-directory-dimitris-p-/

"Too many redirects" wazuh redirect to OIDC but loops starting again

Configuration:
```
server.host: 0.0.0.0
server.port: 5601
opensearch.hosts: https://indexer:9200
opensearch.ssl.verificationMode: none
opensearch.requestHeadersWhitelist: [ authorization,securitytenant ]
opensearch_security.multitenancy.enabled: false
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
server.ssl.enabled: true
server.ssl.key: "/usr/share/wazuh-dashboard/config/certs/key.pem"
server.ssl.certificate: "/usr/share/wazuh-dashboard/config/certs/cert.pem"
opensearch.ssl.certificateAuthorities: ["/usr/share/wazuh-dashboard/config/certs/root-ca.pem"]
uiSettings.overrides.defaultRoute: /app/wazuh
opensearch_security.auth.type: "openid"
opensearch_security.openid.connect_url: "https://keycloakurl/auth/realms/realm/.well-known/openid-configuration"
opensearch_security.openid.client_id: "client-siem"
opensearch_security.openid.client_secret: "clientpasword"
opensearch.username: "kibanaserver"
opensearch.password: "kibanaserver"
opensearch_security.openid.base_redirect_url: https://siemurl
```

Mount  config.yaml as configmap does not overwrite order, they keep sticky of Wazuh Management

```
---

# This is the main OpenSearch Security configuration file where authentication
# and authorization is defined.
#
# You need to configure at least one authentication domain in the authc of this file.
# An authentication domain is responsible for extracting the user credentials from
# the request and for validating them against an authentication backend like Active Directory for example.
#
# If more than one authentication domain is configured the first one which succeeds wins.
# If all authentication domains fail then the request is unauthenticated.
# In this case an exception is thrown and/or the HTTP status is set to 401.
#
# After authentication authorization (authz) will be applied. There can be zero or more authorizers which collect
# the roles from a given backend for the authenticated user.
#
# Both, authc and auth can be enabled/disabled separately for REST and TRANSPORT layer. Default is true for both.
#        http_enabled: true
#        transport_enabled: true
#
# For HTTP it is possible to allow anonymous authentication. If that is the case then the HTTP authenticators try to
# find user credentials in the HTTP request. If credentials are found then the user gets regularly authenticated.
# If none can be found the user will be authenticated as an "anonymous" user. This user has always the username "anonymous"
# and one role named "anonymous_backendrole".
# If you enable anonymous authentication all HTTP authenticators will not challenge.
#
#
# Note: If you define more than one HTTP authenticators make sure to put non-challenging authenticators like "proxy" or "clientcert"
# first and the challenging one last.
# Because it's not possible to challenge a client with two different authentication methods (for example
# Kerberos and Basic) only one can have the challenge flag set to true. You can cope with this situation
# by using pre-authentication, e.g. sending a HTTP Basic authentication header in the request.
#
# Default value of the challenge flag is true.
#
#
# HTTP
#   basic (challenging)
#   proxy (not challenging, needs xff)
#   kerberos (challenging)
#   clientcert (not challenging, needs https)
#   jwt (not challenging)
#   host (not challenging) #DEPRECATED, will be removed in a future version.
#                          host based authentication is configurable in roles_mapping

# Authc
#   internal
#   noop
#   ldap

# Authz
#   ldap
#   noop

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-index
  namespace: wazuh
data:
  config.yml: |-
    _meta:
      type: "config"
      config_version: 2

    config:
      dynamic:
        # Set filtered_alias_mode to 'disallow' to forbid more than 2 filtered aliases per index
        # Set filtered_alias_mode to 'warn' to allow more than 2 filtered aliases per index but warns about it (default)
        # Set filtered_alias_mode to 'nowarn' to allow more than 2 filtered aliases per index silently
        #filtered_alias_mode: warn
        #do_not_fail_on_forbidden: false
        #kibana:
        # Kibana multitenancy
        #multitenancy_enabled: true
        #server_username: kibanaserver
        #index: '.kibana'
        http:
          anonymous_auth_enabled: false
          xff:
            enabled: false
            internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
            #internalProxies: '.*' # trust all internal proxies, regex pattern
            #remoteIpHeader:  'x-forwarded-for'
            ###### see https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html for regex help
            ###### more information about XFF https://en.wikipedia.org/wiki/X-Forwarded-For
            ###### and here https://tools.ietf.org/html/rfc7239
            ###### and https://tomcat.apache.org/tomcat-8.0-doc/config/valve.html#Remote_IP_Valve
        authc:
          kerberos_auth_domain:
            http_enabled: false
            transport_enabled: false
            order: 6
            http_authenticator:
              type: kerberos
              challenge: true
              config:
                # If true a lot of kerberos/security related debugging output will be logged to standard out
                krb_debug: false
                # If true then the realm will be stripped from the user name
                strip_realm_from_principal: true
            authentication_backend:
              type: noop
          basic_internal_auth_domain:
            description: "Authenticate via HTTP Basic against internal users database"
            http_enabled: true
            transport_enabled: true
            order: 1
            http_authenticator:
              type: basic
              challenge: false
            authentication_backend:
              type: internal
          openid_auth_domain:
            description: "Authenticate x-iam openid"
            http_enabled: true
            transport_enabled: true
            order: 0
            http_authenticator:
              type: openid
              challenge: true
              config:
                subject_key: preferred_username
                roles_key: kibana_server
                openid_connect_url: "https://keycloakurl/auth/realms/ibm/.well-known/openid-configuration"
            authentication_backend:
   ```
Tested:
Opensearch Doc for OpenID support
overwritting config.yaml does not overwrite orders
Reviw wazuh slack channels with some topics related

**Comment by andraspavelbaystream** [comment]
Hello,

Does anybody have any news on this?

Thanks,
Andras

**Comment by landon-lengyel** [comment]
This might be more of a documentation issue than a Wazuh issue... I was able to get mine working with the following and EntraID as my IDP:
The below config gets Wazuh dashboard fully supporting both basic auth, and OpenID Connect.

config.yml
```
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
    authc:
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: preferred_username
            roles_key: roles
            openid_connect_url: {App Registrations > Overview > Endpoints > OpenID Connect metadata document}
            openid_connect_idp:
              enable_ssl: true
              verify_hostnames: true
              #pemtrustedcas_filepath: /etc/opensearch/opensearch-security/DigiCertGlobalRootCA.crt.pem
              pemtrustedcas_content: |-
                -----BEGIN CERTIFICATE-----
               {Certificate}
                -----END CERTIFICATE-----
        authentication_backend:
          type: noop
{Other methods}
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 3
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: internal
```

opensearch_dashboards.yml
```
server.host: 0.0.0.0
opensearch.hosts: https://127.0.0.1:9200
server.port: 443
# opensearch.username: kibanaserver
# opensearch.password: kibanaserver
uiSettings.overrides.defaultRoute: /app/wz-home

# Security settings
opensearch_security.cookie.secure: true
opensearch.requestHeadersAllowlist: ["securitytenant","Authorization"]
opensearch_security.multitenancy.enabled: false
opensearch_security.readonly_mode.roles: ["kibana_read_only"]

# TLS communication from Dashboards to cluster
opensearch.ssl.verificationMode: certificate
opensearch.ssl.certificateAuthorities: ["/etc/wazuh-dashboard/certs/root-ca.pem"]

# TLS communication from clients to Dashboards
server.ssl.enabled: true
server.ssl.key: "/etc/wazuh-dashboard/certs/wazuh.key"
server.ssl.certificate: "/etc/wazuh-dashboard/certs/wazuh.crt"
server.ssl.certificateAuthorities: "/etc/wazuh-dashboard/certs/combined-ca.pem"

## OpenID Authentication (SSO)
opensearch_security.auth.multiple_auth_enabled: true
opensearch_security.auth.type: ["openid","basicauth"]
opensearch_security.openid.base_redirect_url: "{Wazuh URL}"
opensearch_security.openid.connect_url: "{App Registrations > Overview > Endpoints > OpenID Connect metadata document}"
opensearch_security.openid.client_id: "{App Registrations > Overview > Application (client) ID}"
opensearch_security.openid.client_secret: "{App Registrations > Certificates & secrets > Value}"
opensearch_security.openid.root_ca: "/etc/wazuh-dashboard/certsDigiCertGlobalRootCA.crt.pem"
```

**Comment by fontexD** [comment]
> This might be more of a documentation issue than a Wazuh issue... I was able to get mine working with the following and EntraID as my IDP: The below config gets Wazuh dashboard fully supporting both basic auth, and OpenID Connect.
> 
> config.yml
> 
> ```
> _meta:
>   type: "config"
>   config_version: 2
> 
> config:
>   dynamic:
>     http:
>       anonymous_auth_enabled: false
>       xff:
>         enabled: false
>     authc:
>       openid_auth_domain:
>         http_enabled: true
>         transport_enabled: true
>         order: 1
>         http_authenticator:
>           type: openid
>           challenge: false
>           config:
>             subject_key: preferred_username
>             roles_key: roles
>             openid_connect_url: {App Registrations > Overview > Endpoints > OpenID Connect metadata document}
>             openid_connect_idp:
>               enable_ssl: true
>               verify_hostnames: true
>               #pemtrustedcas_filepath: /etc/opensearch/opensearch-security/DigiCertGlobalRootCA.crt.pem
>               pemtrustedcas_content: |-
>                 -----BEGIN CERTIFICATE-----
>                {Certificate}
>                 -----END CERTIFICATE-----
>         authentication_backend:
>           type: noop
> {Other methods}
>       basic_internal_auth_domain:
>         description: "Authenticate via HTTP Basic against internal users database"
>         http_enabled: true
>         transport_enabled: true
>         order: 3
>         http_authenticator:
>           type: basic
>           challenge: false
>         authentication_backend:
>           type: internal
> ```
> 
> opensearch_dashboards.yml
> 
> ```
> server.host: 0.0.0.0
> opensearch.hosts: https://127.0.0.1:9200
> server.port: 443
> # opensearch.username: kibanaserver
> # opensearch.password: kibanaserver
> uiSettings.overrides.defaultRoute: /app/wz-home
> 
> # Security settings
> opensearch_security.cookie.secure: true
> opensearch.requestHeadersAllowlist: ["securitytenant","Authorization"]
> opensearch_security.multitenancy.enabled: false
> opensearch_security.readonly_mode.roles: ["kibana_read_only"]
> 
> # TLS communication from Dashboards to cluster
> opensearch.ssl.verificationMode: certificate
> opensearch.ssl.certificateAuthorities: ["/etc/wazuh-dashboard/certs/root-ca.pem"]
> 
> # TLS communication from clients to Dashboards
> server.ssl.enabled: true
> server.ssl.key: "/etc/wazuh-dashboard/certs/wazuh.key"
> server.ssl.certificate: "/etc/wazuh-dashboard/certs/wazuh.crt"
> server.ssl.certificateAuthorities: "/etc/wazuh-dashboard/certs/combined-ca.pem"
> 
> ## OpenID Authentication (SSO)
> opensearch_security.auth.multiple_auth_enabled: true
> opensearch_security.auth.type: ["openid","basicauth"]
> opensearch_security.openid.base_redirect_url: "{Wazuh URL}"
> opensearch_security.openid.connect_url: "{App Registrations > Overview > Endpoints > OpenID Connect metadata document}"
> opensearch_security.openid.client_id: "{App Registrations > Overview > Application (client) ID}"
> opensearch_security.openid.client_secret: "{App Registrations > Certificates & secrets > Value}"
> opensearch_security.openid.root_ca: "/etc/wazuh-dashboard/certsDigiCertGlobalRootCA.crt.pem"
> ```

how did u get it to accept the openid root_ca ? i keep getting the error i posted below, tried alot of diff things :(  (new to wazuh) ive done this in opensearch no problem, but this is just outta this world , runing latest 4.12.x

**Comment by landon-lengyel** [comment]
@fontexD Can you share what your `opensearch-dashboards.yml` and `config.yml` look like? Be sure to redact any sensitive information.

In my case I went to the AzureAD/EntraID OpenID endpoint in my web browser and found that their root CA was that DigiCertGlobalRootCA. Then I downloaded a copy of that certificate and used it for those files.
In your case I assume it would be https://dex.mydomain.org

**Comment by nicleary** [comment]
Jumping in here with my own:

I've configured Wazuh to communicate with a Keycloak server. When I hit Wazuh, I select the single sign on link from the login screen, and am successfully redirected to keycloak. I sign in via Keycloak, and then am redirected back to Wazuh, where I get a 401 unauthorized error. 

The logs for the dashboard simply state 

`{"type":"log","@timestamp":"2025-06-16T14:52:02Z","tags":["error","plugins","securityDashboards"],"pid":55,"message":"OpenId authentication failed: Error: Authentication Exception"}`

The logs for the indexer however seem to indicate that there's some sort of SSL error in connecting to keycloak:

```
[2025-06-16T14:52:02,891][WARN ][o.o.s.a.BackendRegistry  ] [wazuh-indexer-0] Authentication finally failed for null from 10.42.0.49:60722
[2025-06-16T14:52:02,891][WARN ][c.a.d.a.h.j.k.SelfRefreshingKeySet] [wazuh-indexer-0] KeySetProvider threw error
com.amazon.dlic.auth.http.jwt.keybyoidc.AuthenticatorUnavailableException: Error while getting https://<keycloak domain>/realms/wazuh/.well-known/openid-configuration: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at com.amazon.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.getJwksUri(KeySetRetriever.java:167) ~[opensearch-security-2.16.0.0.jar:2.16.0.0]
        at com.amazon.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.get(KeySetRetriever.java:72) ~[opensearch-security-2.16.0.0.jar:2.16.0.0]
        at com.amazon.dlic.auth.http.jwt.keybyoidc.SelfRefreshingKeySet$1.run(SelfRefreshingKeySet.java:213) [opensearch-security-2.16.0.0.jar:2.16.0.0]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) [?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:130) ~[?:?]
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:378) ~[?:?]
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321) ~[?:?]
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:316) ~[?:?]
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1318) ~[?:?]
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1195) ~[?:?]
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1138) ~[?:?]
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:393) ~[?:?]
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:476) ~[?:?]
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:447) ~[?:?]
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201) ~[?:?]
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426) ~[?:?]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar:4.5.13]
        at com.amazon.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.getJwksUri(KeySetRetriever.java:140) ~[opensearch-security-2.16.0.0.jar:2.16.0.0]
        ... 7 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:388) ~[?:?]
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:271) ~[?:?]
        at java.base/sun.security.validator.Validator.validate(Validator.java:256) ~[?:?]
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:230) ~[?:?]
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132) ~[?:?]
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1302) ~[?:?]
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1195) ~[?:?]
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1138) ~[?:?]
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:393) ~[?:?]
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:476) ~[?:?]
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:447) ~[?:?]
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201) ~[?:?]
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426) ~[?:?]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar:4.5.13]
        at com.amazon.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.getJwksUri(KeySetRetriever.java:140) ~[opensearch-security-2.16.0.0.jar:2.16.0.0]
        ... 7 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:148) ~[?:?]
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:129) ~[?:?]
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297) ~[?:?]
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:383) ~[?:?]
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:271) ~[?:?]
        at java.base/sun.security.validator.Validator.validate(Validator.java:256) ~[?:?]
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:230) ~[?:?]
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132) ~[?:?]
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1302) ~[?:?]
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1195) ~[?:?]
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1138) ~[?:?]
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:393) ~[?:?]
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:476) ~[?:?]
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:447) ~[?:?]
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201) ~[?:?]
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455) ~[?:?]
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426) ~[?:?]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.13.jar:4.5.13]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar:4.5.13]
        at com.amazon.dlic.auth.http.jwt.keybyoidc.KeySetRetriever.getJwksUri(KeySetRetriever.java:140) ~[opensearch-security-2.16.0.0.jar:2.16.0.0]
        ... 7 more
```

When I use `curl https://<keycloak domain>/realms/wazuh/.well-known/openid-configuration --cacert /usr/share/wazuh-indexer/certs/root-ca.pem` from within the indexer container, I successfully get the OIDC connection information, so I don't believe this is an issue with my certificates themselves.

My (redacted) opensearch security config:

```
---
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 7
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 9
        http_authenticator:
          type: openid
          challenge: true
          config:
            subject_key: preferred_username
            roles_key: roles
            openid_connect_url: "https://<keycloak domain>/realms/wazuh/.well-known/openid-configuration"
            openid_connect_idp:
              enable_ssl: true
              pemtrustedcas_filepath: "/usr/share/wazuh-indexer/certs/root-ca.pem"
            client_id: "wazuh"
            client_secret: "SoSecure"
        authentication_backend:
          type: noop
```

And my opensearch dashboards config:

```
server.host: 0.0.0.0
server.port: 5601
opensearch.hosts: https://indexer:9200
opensearch.ssl.verificationMode: none
opensearch.requestHeadersWhitelist: [ authorization,securitytenant ]
opensearch_security.multitenancy.enabled: false
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
server.ssl.enabled: true
server.ssl.key: "/usr/share/wazuh-dashboard/certs/key.pem"
server.ssl.certificate: "/usr/share/wazuh-dashboard/certs/cert.pem"
opensearch.ssl.certificateAuthorities: ["/usr/share/wazuh-dashboard/certs/root-ca.pem"]
uiSettings.overrides.defaultRoute: /app/wz-home

opensearch_security.auth.multiple_auth_enabled: true
opensearch_security.auth.type: ["openid","basicauth"]

# The IdP metadata endpoint
opensearch_security.openid.connect_url: "https://<keycloak domain>/realms/wazuh/.well-known/openid-configuration"

# The ID of the OpenID Connect client in your IdP
opensearch_security.openid.client_id: "wazuh"

# The client secret of the OpenID Connect client
opensearch_security.openid.client_secret: "SoSecret"
opensearch_security.openid.root_ca: "/usr/share/wazuh-dashboard/certs/root-ca.pem"
opensearch_security.openid.base_redirect_url: "<Wazuh Dashboard URL>"
```

Any ideas?
